---
hw_ha_deploy_mode: double                 # ha_deploy_mode default value
ha_deploy_mode: "{{ hw_ha_deploy_mode }}" # double : HA deployment mode. HA can be deployed on a single node or two nodes. FusionStorage only supports the two-node deployment mode.
hw_net_mode: single                       # net_mode default value
net_mode: "{{ hw_net_mode }}"             # single/double : Management plane deployment mode. Single management plane and dual management planes (internal and external planes) are supported. In the single-management plane deployment mode, the external and internal IP addresses are the same.
service_float_ip: &service_float_ip_config # External management floating IP address. The value is the same as the internal floating IP address in the single-management plane deployment mode.
  "{{ hw_master_float_address }}"
service_local_ip: &service_local_ip_config # External management IP address of FSM 1. The value is the same as the internal management IP address in the single-management plane deployment mode.ss
  "{{ hw_master_local_address }}"
master_login_pwd: "{{ hw_master_root_login_pwd }}"   # Password of user root used for logging in to FSM 1 using SSH.
service_remote_ip: &service_remote_ip_config         # External management IP address of FSM 2. The value is the same as the internal management IP address in the single-management plane deployment mode.
  "{{ hw_remote_address }}"
slave_login_pwd: "{{ hw_remote_root_login_pwd }}"    # Password of user root used for logging in to FSM 2 using SSH.
local_sn: 
remote_sn: 
local_cabinet: 
remote_cabinet: 
service_gateway:
service_mask:
service_local_port:
service_remote_port:
manager_float_ip: *service_float_ip_config
float_ip_for_ha: *service_float_ip_config
manager_gateway:
manager_mask:
manager_local_ip: *service_local_ip_config
manager_local_port:
manager_remote_ip: *service_remote_ip_config
manager_remote_port:
local_host_name:
remote_host_name:
pk_b:
login_user_name:
login_user_pwd: 
login_pwd:
remote_login_user_name:
remote_login_user_pwd: 
remote_login_pwd:
