ha_role: primary
init_role: primary
local_sn: 
remote_sn: 
local_cabinet: 
remote_cabinet: 
ha_mode: double
net_mode: single
service_float_ip: 10.183.144.46
service_gateway: 10.183.144.1
service_mask: 255.255.254.0
service_local_ip: 10.183.144.186
service_local_port: eth0
service_remote_ip: 10.183.144.161
service_remote_port: eth0
manager_float_ip: 10.183.144.46
float_ip_for_ha: 10.183.144.46
manager_gateway: 10.183.144.1
manager_mask: 255.255.254.0
manager_local_ip: 10.183.144.186
manager_local_port: eth0
manager_remote_ip: 10.183.144.161
manager_remote_port: eth0
local_host_name: ctuphisprb00472
remote_host_name: ctuphisprb00475
pk_b: ySaVXoWz3GV3FJoBMCXr8Q==
login_user_name: 
login_user_pwd: 
login_pwd: sha256.1562.zZ_HB56gSwhj4JlWG-yuHGSbas16KAuEf8REjwQnJXVtKs2vXgO6zOkGzo0OFX622gsKEjuIQ7M=
remote_login_user_name: 
remote_login_user_pwd: 
remote_login_pwd: sha256.1192.bXsGpM2WZSZ3_l80C9J5HJ41-A3196m2EylPDdYUmsFJbFOnQ7-jbTHi7J9Kh4qlqjfs_5roTy0=
