---
- hosts: fsm-master
  gather_facts: no
  collections:
    - oceanstor_series.oceanstor
  tasks:
    - import_role:
        name: hw_oceanstor_management
      tags: master

- hosts: localhost
  gather_facts: no
  collections:
    - oceanstor_series.oceanstor
  remote_user: root
  tasks:
    - debug:
        msg: "Begin to install OceanStor storage"
    - import_role:
        name: hw_oceanstor_storage
      tags: local