---
# tasks file for hw_oceanstor_storage
- name: Change OceanStor default password
  hw_oceanstor_manage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ default_api_password }}"
    validate_certs: false
    param:
      new_password: "{{ api_password }}"
    function: "modify_user_password"
  tags: 
    - change-password

- name: Get OceanStor Auth token
  hw_oceanstor_manage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    validate_certs: false
    function: "get_token"
  become: yes
  register: token
  tags:
    - always
    - restore_factory
    - add-storage
    - storage

- name: Set api-token factor
  set_fact: api_token={{ token.token }}
  tags:
    - always
    - restore_factory
    - add-storage
    - storage

- name: Restore factory for OceanStor storage
  hw_oceanstor_manage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    validate_certs: false
    token: "{{ api_token }}"
    function: "restore_factory"
  when: "{{ restore_factory }}==true"
  tags: 
    - restore_factory

- name: Add Huawei OceanStor Storage
  hw_oceanstor_add_storage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    servers: "{{ server_list }}"
    default_root_password: "{{ server_default_root_password }}"
    step: "add_node"
  become: yes
  tags: 
    - storage
    - add-storage

- name: Check Add Huawei OceanStor Storage status
  hw_oceanstor_add_storage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    service_type: "agent"
    servers: "{{ server_list }}"
    step: "check_add_storage_status"
  become: yes
  register: result
  until: "result.status=='success' or result.status=='fail'"
  retries: 50
  delay: 5
  tags: 
    - storage
    - add-storage

- name: Exit if add OceanStor task failture
  fail: msg="fail"
  when: result.status=='fail'
  tags: 
    - storage
    - add-storage

- name: Install Huawei OceanStor Storage FSA
  hw_oceanstor_add_storage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    service_type: "agent"
    servers: "{{ server_list }}"
    step: "install_node"
  become: yes
  tags: 
    - storage
    - add-storage

- name: Check Install Huawei OceanStor Storage FSA status
  hw_oceanstor_add_storage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    service_type: "agent"
    servers: []
    step: "check_status"
  become: yes
  register: result
  until: "result.status=='success' or result.status=='failure'"
  retries: 50
  delay: 5
  tags: 
    - storage
    - add-storage

- name: Exit if Install Storage FSA task failture
  fail: msg="fail"
  when: result.status=='failure'
  tags: 
    - storage
    - add-storage

- name: Config OceanStor Storage frontend network
  hw_oceanstor_config_network:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    network_param: "{{ storage_network.storage_frontend_network }}"
    network_type: "storage_frontend"
    step: "config_network"
  tags: network

- name: Config OceanStor Storage backend network
  hw_oceanstor_config_network:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    network_param: "{{ storage_network.storage_backend_network }}"
    network_type: "storage_backend"
    step: "config_network"
  tags: network

- name: Validity OceanStor Storage frontend network
  hw_oceanstor_config_network:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    network_param: "{{ storage_network.storage_frontend_network }}"
    network_type: "storage_frontend"
    step: "validity_network"
  tags: network

- name: Validity OceanStor Storage backend network
  hw_oceanstor_config_network:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    network_param: "{{ storage_network.storage_backend_network }}"
    network_type: "storage_backend"
    step: "validity_network"
  tags: network

- name: Install Huawei OceanStor Storage all
  hw_oceanstor_add_storage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    service_type: "all"
    servers: "{{ server_list }}"
    step: "install_node"
  become: yes
  tags: 
    - storage
    - install-storage

- name: Check Install Huawei OceanStor Storage status
  hw_oceanstor_add_storage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    token: "{{ api_token }}"
    servers: "{{ server_list }}"
    service_type: "all"
    step: "check_status"
  become: yes
  register: result
  until: "result.status=='success' or result.status=='failure'"
  delay: 5
  retries: 100
  tags:
    - storage
    - install-storage

- name: Exit if install OceanStor task failture
  fail: msg="fail"
  when: result.status=='failure'
  tags:
    - storage
    - install-storage

- name: "Create OceanStor manage cluster"
  hw_oceanstor_manage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    validate_certs: false
    token: "{{ api_token }}"
    function: "create_manage_cluster"
    param: "{{ manage_cluster }}"
  become: yes
  tags:
    - storage
    - mdc

- name: Uploading the License
  hw_oceanstor_manage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ default_api_password }}"
    validate_certs: false
    param:
      license_file_name: "{{ filename }}"
    function: "uploading_license"
    tags:
      - never
      - uploading-license

- name: "Create OceanStor storage pool"
  hw_oceanstor_manage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    validate_certs: false
    token: "{{ api_token }}"
    function: "create_storage_pool"
    param:
      poolName: "{{ oceanstor_pool.name }}"
      serviceType: "{{ oceanstor_pool.service_type }}"
      encryptType: "{{ oceanstor_pool.encryt_type }}"
      storageMediaType: "{{ oceanstor_pool.main_media_type }}"
      cacheMediaType: "{{ oceanstor_pool.cache_media_type }}"
      compressionAlgorithm: "{{ oceanstor_pool.compression_algorithm }}"
      redundancyPolicy: "{{ oceanstor_pool.redundancy_policy }}"
      replicaNum: "{{ oceanstor_pool.replica_num }}"
      securityLevel: "{{ oceanstor_pool.security_level }}"
      numDataUnits: "{{ oceanstor_pool.num_data_units }}"
      numParityUnits: "{{ oceanstor_pool.num_parity_units }}"
      numFaultTolerance: "{{ oceanstor_pool.num_fault_tolerance }}"
      serverList: "{{ oceanstor_pool.server_list }}"
  become: yes
  register: pool_task
  tags:
    - storage
    - create-pool

- name: Check create OceanStor storage pool progress
  hw_oceanstor_manage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    validate_certs: false
    token: "{{ api_token }}"
    function: "query_task_info"
    param:
      taskId: "{{ pool_task.taskId }}"
  become: yes
  register: progress
  until: "progress.task.taskStatus=='success' or progress.task.taskStatus=='failed'"
  delay: 5
  retries: 25
  tags:
    - storage
    - create-pool

- name: "Create VBS client"
  hw_oceanstor_manage:
    api_url: "{{ manager_float_ip }}"
    api_port: "{{ api_port }}"
    username: "{{ api_username }}"
    password: "{{ api_password }}"
    validate_certs: false
    token: "{{ api_token }}"
    function: "create_vbs_client"
    param:
      vbs_list: "{{ vbs_list }}"
  become: yes
  register: result
  tags:
    - storage
    - create-VBS

- name: "Print result of create VBS client "
  debug: var=result.msg
  tags:
    - storage
    - create-VBS

- name: "Exit if create VBS client failture"
  fail: msg="fail"
  when: result.status=='failure'
  tags:
    - storage
    - create-VBS