---
# tasks file for hw_oceanstor_management
- name: Make sure dir /opt/fusionstorage/repository/deploymanager_pkg/DSwareSoft/ not exists
  file:
    path: "{{ oceanstor_deploymanager_dir }}"
    state: absent
  become: yes
  tags: fsm

- name: Upload OceanStor artifact file to the first FSM node
  copy:
    src: "{{ item }}"
    dest: "{{ oceanstor_deploymanager_dir }}"
    owner: root
    group: root
    mode: u+rw,g-wx,o-rwx
  become: yes
  tags: fsm
  with_fileglob:
      - /opt/workspace/OceanStor_100D_{{oceanstor_artifact_version}}*.tar.gz

- name: Find deploymanager folder path
  command: find {{ oceanstor_deploymanager_dir }} -name "OceanStor_100D_{{oceanstor_artifact_version}}*"
  register: oceanstor_artifact_name
  tags: fsm
  become: yes

- name: Show OceanStor artifact file name
  debug: var=oceanstor_artifact_name
  become: yes
  tags: fsm

- name: Extract OceanStor artifact into /opt/fusionstorage/repository/deploymanager_pkg/DSwareSoft/
  unarchive:
    src: "{{ oceanstor_artifact_name.stdout }}"
    dest: "{{ oceanstor_deploymanager_dir }}"
    remote_src: yes
  become: yes
  tags: fsm

- name: Find deploymanager folder path
  command: find {{ oceanstor_deploymanager_dir }} -name "deploymanager"
  register: deploymanager_path
  become: yes
  tags: fsm

- name: show deploymanager_path
  debug: var=deploymanager_path
  tags: fsm

- name: Copy deploymanager files to folder /opt/fusionstorage/repository/deploymanager_pkg/DSwareSoft/
  shell: "cp -r {{ deploymanager_path.stdout }}/* {{ oceanstor_deploymanager_dir }}"
  become: yes
  tags: fsm

- name: Generate HAInfoFromInstallTool.properties in folder /home
  template:
    src: "HAInfoFromInstallTool.properties.j2"
    dest: "/home/HAInfoFromInstallTool.properties"
  become: yes
  tags: fsm

- name: Run install.sh on the first FSM node
  shell: "sh {{ oceanstor_deploymanager_dir }}/install.sh"
  become: yes
  tags: fsm
